### ISSUE TITLE
Transfer / Chamber

### ISSUE THREAD

**Issue by MariyaVla** [sta-titansrobotics/19446-IntoTheDeep#14]
This is going to be designed in Onshape and assembled with all the different components to form an intake design. From there when all the parts are established they will be printed out for prototype and testing.

From a driver's perspective I want the chamber to be reliable in transferring the sample from the pick up and into the outtake. It should be stable and easily hold onto the sample so that when driving quickly or shaking during motion, the sample is secure within the box and doesn't fall out or shift around. 

The chamber should have a tolerance / extra space so that when the sample is going in there is room for error.
The chamber should be able to hold in the sample under ANY conditions except when letting the sample move onto outtake.
The chamber should be heavy enough / thick enough not to break easily if vigorously shaken. 
The transfer should be reliable and work without getting the sample stuck on any edges or corners and should easily pass on the sample from the pick up to chamber. 

The chamber must be compatible with the trapdoor / outtake claw so that the sample can easily be transferred out of the chamber to score.

**Comment by MariyaVla** [comment]
Sept 23 Progress:
Today I started the CAD for the chamber and was working on different dimensions with Gian so that it could properly connect to the outtake. I was also making sure to check in with Cameron so that the intake pick up would properly transfer into the chamber. 

<img width="662" alt="image" src="https://github.com/user-attachments/assets/0d79b37f-d994-4751-8237-075401962601">

**Comment by MariyaVla** [comment]
Sept 24 Progress:
Last night I had printed out the intake chamber so that I could assemble it with Gian's claw. The dimensions worked well in person and the design worked well with Gian's claw. I also helped assign more issues with everyone and organize ideas today while gian was testing out the claw. I hope to establish a clearer idea of the onshape design with a couple prototype iterations by the end of this week.

**Comment by GianBangayan** [comment]
![image](https://github.com/user-attachments/assets/54fbbf19-896b-414f-8922-b760ed05cd87)

https://github.com/user-attachments/assets/e10db878-8eec-4c17-adc3-7bcbc0195793

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/b018e3fe-5408-4c80-b203-4ca1c7e54721)
- Made walls slightly larger
- Added center hole for rubberbanding
- Added upper corner holes for trapdoor rotation point

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/7d8f137b-068b-4972-9b3d-731aa8890948)
- Updated corners to allow the trapdoor to move over it (no interference) and also cut off part of the corner

Further discussion tomorrow to make sure this won't affect anything else, and a few more changes I want to discuss and consider.

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/ebb36c77-be84-441f-a078-c0c843d6bea5)
- Increased length of chamber and shifted rotation points in order to fix one of the issues discussed in #15 (regarding the sample hitting the axle on the way up)
