### ISSUE TITLE
Outtake Design / Prototype

### ISSUE THREAD

**Issue by MariyaVla** [sta-titansrobotics/19446-IntoTheDeep#16]
Log of outtake, build and testing. Outtake includes all the systems required for scoring points by outputting game objects, including samples and specimens. Has records of alternative/previous versions of designs and creations.

**Comment by GianBangayan** [comment]
https://github.com/sta-titansrobotics/19446-IntoTheDeep/issues/5#issuecomment-2371996301

**Comment by GianBangayan** [comment]
https://github.com/user-attachments/assets/0365a14f-f492-4814-9d4b-3ac7360f915c

https://github.com/user-attachments/assets/fc757fd5-d619-486d-bfe6-f3db77b34b7d

https://github.com/user-attachments/assets/613d8728-d5b4-43b3-901d-9766932514d2
