### ISSUE TITLE
Sprint 2 - Intake

### ISSUE THREAD

**Issue by MariyaVla** [sta-titansrobotics/19446-IntoTheDeep#24]
We are aiming to complete our intake by the end of this sprint. The intake is going to be designed within Onshape. The various parts of the intake (ramp and funnel) will be designed within the intake, and will be put together in an intake-specific assembly, and placed inside the assembly of the entire robot. All portions of the intake will be printed, tested, and iterated upon as needed.

At a high level, the intake must be able to effectively and efficiently intake samples. This means:
- There must not be any jamming in the intake (the samples should not get stuck anywhere)
- The motor spins fast enough

From a driver's perspective, the intake must be wide enough to easily retrieve samples without much precision from the drivers. However, it shouldn't be too wide that multiple samples can enter (we want a maximum of 1 to avoid penalties).

From a structural perspective, the intake must be mounted securely and not interfere with other parts. This means that there shouldn't be much shaking when the intake is moving on the sliders.

Furthermore, the intake includes the horizontal sliders, so it is ideal to have those mounted by the end of Sprint 2 as well.

-@Ethan-Selvarajah

**Comment by MariyaVla** [comment]
This week we have made a new design to better implement a ramp and add all the new components and remove the previous ones that were making the intaking process more difficult. On our new intake design, we are implementing a detached ramp which is going to be the only movable part. This will help the ramp go over the barrier surrounding the samples without having to use a motor to move the whole component including the actual motors and surgical tubing mounting. The Ramp is attached on a singular servo since it is light weight. Then, there is a component that is used as walls on the side of the ramp which are crooked and different angles so that the sample wouldn't get stuck sideways during intake. These angles allow the sample to rearrange itself to be carefully placed into the chamber with the top wall holding down the sample so that it doesn't slip out through the top. After this intake the sample ig going to go into the chamber which is attached to the sliders with standoffs. 

![image](https://github.com/user-attachments/assets/349ac606-c014-418d-baac-37ebe380ea7a)

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/065e704d-b466-44db-b75f-04be6a464166)
![image](https://github.com/user-attachments/assets/2f55e191-65dd-4488-a6cc-8376a8b4afe8)
- Funnel was updated
- - Different angles on either side to help guide the sample inwards
- - Roller mount was lowered so that it can reach the floor and past the ramp
- - Roof was removed
- Ramp was updated
- - Dimensions changed to make it fit more cohesively with the funnel

-@cameronso5 @Ethan-Selvarajah

**Comment by MariyaVla** [comment]
For chamber I have made unjustements to add some trapdoors to help hold the sample down rather than fly out during the intake. I also changed the adjustments to fit one claw prong rather than two we had before. So in summary:

- Shortened Chamber
- Added Trapdoors for Transfers
- Change from 1 cut out to 2 cut outs for new claw
- Adjust mounting of screws with new trapdoor

![image](https://github.com/user-attachments/assets/10be7334-10f4-4b1e-999f-3f4d9f09b476)

**Comment by MariyaVla** [comment]
Keeping in mind the objectives of the chamber and trap door:
- The sample should have no restrains in passing into the chamber
- The sample shouldn't be able to escape the chamber until the claw pulls it out
- The claw should be able to easily grab the sample without getting caught or stuck
- The trapdoors should easily open and snap back into place at a 90 degree angle, without going 100% back down

The previous chamber has went through printing and has been edited to fix more of its flaws throughout the past few days. 
- I made sure that the fit of the trapdoor wouldn't be too tight onto the chamber 
- I flipped the position of the hook so that it would be easier to create tension and easier to print 
- I added two holes so that the rubber band could pass through the trapdoor and out onto the outside of the chamber (keeping in mind that I don't want the rubber bands to stop the sample from passing in)
- I adjusted the side of the ingrave for the claw since it was too small and had gotten stuck a couple times when testing grabbing mechanism
- I removed an area of the fillet from the inside of the trapdoor so that instead of going all the way back down and hitting the wall, it would get stopped by a flat surface and would stop at a 90 degree angle
- Finally, I added a small notch at the back so that i could tie off the rubberband there, this will be printed to test out and go through iterations

![image](https://github.com/user-attachments/assets/a7db5e5d-19a7-4c2d-8752-7216aec5ac27)

![image](https://github.com/user-attachments/assets/dddf0d25-fd58-4249-8d6e-8bdf0739e4fb)

![image](https://github.com/user-attachments/assets/98e3e58a-6c3a-46a0-8690-2bdf55e21277)
