### ISSUE TITLE
Outtake

### ISSUE THREAD

**Issue by GianBangayan** [sta-titansrobotics/19446-IntoTheDeep#5]
Outtake includes all the systems required for scoring points by outputting game objects, including samples and specimens.

**Comment by GianBangayan** [comment]
Initial claw revision (V1)
![image](https://github.com/user-attachments/assets/1f0ec34d-55bb-4087-a2fa-44706456a2d8)
- Clips onto specimen from wall
- Potential for breakage along clip wall
- Lack of auto-centering/funnel in front

Claw V2
![image](https://github.com/user-attachments/assets/8ea56531-0e2f-4457-a70a-f0c57883e38a)
- improves life of repeated use 
- Reduces force for pulling down specimens
- added funnel auto-centering

Claw V3
![image](https://github.com/user-attachments/assets/56ed18e7-a866-4244-b084-7ed40ba4e7be)
- Improves down pull force
- changes? (not sure if it's better or worse) lifespan

**Comment by GianBangayan** [comment]
Claw V3 (old) Intial Tesiting 
https://github.com/user-attachments/assets/c8df09ea-2396-4eb5-b9fa-038dab20cf89
- noticed it didn't have enough down-force to pull it down
- Noticed wear on joints/lines indicating wear after 50+ uses

**Comment by GianBangayan** [comment]
Bucket is very reliant on the intake method and transfer, so further information on that is needed before proceeding with bucket design.

3 Options
- Container + arm 
Pros
- simple
- arm helps reach upwards towards bucket and increases speed
- fast/reliable
Cons
- questionable rule-breaking? (letting it go/ it flying/falling?)
- programmers have to make macro/harder for driver to aim
- questionable transfer

- Container + flaps/tubing + arm
![image](https://github.com/user-attachments/assets/542b2f1f-3ce2-45e1-8e5b-602ae22172a8)
Pros
- Same as above
- Holds blocks for a few ms longer before releasing
Cons
- same (without Rule breaking)
- May need more force from the arm to release

- Container + active release
Pros
- simple
- fast/reliable
- easy to aim/control/less risk of drop/consistency
Cons
- questionable transfer
- slower than one with an arm

**Comment by mrfabroa** [comment]
@GianBangayan need to document the use of the claw for outtake.  As in Ethan F's transfer claw

**Comment by GianBangayan** [comment]
We decided to go with an active claw after discussing potential robot designs to aid in a faster and more consistent transfer.

**Comment by GianBangayan** [comment]
Version 1 Claw, used 1 or 2 servos? was confused about power transfer from one arm to another, Didn't want to use gears.
![image](https://github.com/user-attachments/assets/d9fca089-8207-4158-a75a-3cd13ed644a0)

Version 2 Claw, uses 1 servo, using a crankshaft to power both arms, entirely 3d printed, lack of mounting points
![image](https://github.com/user-attachments/assets/292b86ad-72e8-43cf-9d62-9be797facbfc)

Version 3 Claw, better version 2 claw, servo is mounted to a metal bracket to the rest of the plastic structure, it's stronger overall and the plastic is lighter. Has a metal mounting point and can be connected to arm easily.
![image](https://github.com/user-attachments/assets/14560157-37aa-43cb-8d87-59f91284284f)
