### ISSUE TITLE
Drivetrain

### ISSUE THREAD

**Issue by Erick-Meza** [sta-titansrobotics/19446-IntoTheDeep#8]

**Comment by cameronso5** [comment]
<img width="576" alt="Untitled" src="https://github.com/user-attachments/assets/bfad96da-03a7-4b00-ab45-be42bdb12016">

**Comment by cameronso5** [comment]
<img width="576" alt="Untitled" src="https://github.com/user-attachments/assets/1eb01b91-0bf8-4103-b045-0699a7a8d10f">

**Comment by mrfabroa** [comment]
@cameronso5 need a side view sketch of the drive train.  Height-wise where do those intake sliders go?
