### ISSUE TITLE
Sprint 1 - Design/Build/Test/Revise Iteration 1

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/19446-IntoTheDeep#9]
List objectives for this sprint here as a task list and convert them to issues.  Set all issues for this sprint to the Sprint 1 Milestone

**Comment by Erick-Meza** [comment]
Here are objectives for Sprint 1:

- [ ] Functioning Claw Iteration (Outtake)
- [ ] Durable Climbing Design (Climb/Hang)

**Comment by MariyaVla** [comment]
[] - #12

**Comment by MariyaVla** [comment]
This is the issue for the Claw design that helps transfer the sample from the intake and into the buckets and possibly hang specimens:
#16
